AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Layout/LineLength:
  Max: 100
  IgnoreCopDirectives: true
  Exclude:
    - 'simple_segment.gemspec'

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false